// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbgen

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, client_id, name, email, password_hash, created_at)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type CreateUserParams struct {
	ID           string
	ClientID     string
	Name         string
	Email        string
	PasswordHash []byte
	CreatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.ClientID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, client_id, name, email, password_hash, created_at
FROM users
WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
