// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package dbgen

import (
	"context"
	"time"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, client_id, name, digest, created_at, expires_at)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type CreateAPIKeyParams struct {
	ID        string
	ClientID  string
	Name      string
	Digest    []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.ClientID,
		arg.Name,
		arg.Digest,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const findAPIKey = `-- name: FindAPIKey :one
SELECT id, client_id, name, digest, created_at, expires_at, revoked_at
FROM api_keys
WHERE id = $1
`

func (q *Queries) FindAPIKey(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, findAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Digest,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, client_id, name, created_at, expires_at, revoked_at
FROM api_keys
WHERE client_id = $1
ORDER BY created_at DESC, id
`

type ListAPIKeysRow struct {
	ID        string
	ClientID  string
	Name      string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt *time.Time
}

func (q *Queries) ListAPIKeys(ctx context.Context, clientID string) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
SET revoked_at = COALESCE(revoked_at, $1::timestamptz)
WHERE id = $2 AND client_id = $3
`

type RevokeAPIKeyParams struct {
	RevokedAt time.Time
	ID        string
	ClientID  string
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.RevokedAt, arg.ID, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
