// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package dbgen

import (
	"context"
	"time"
)

const createClient = `-- name: CreateClient :exec
INSERT INTO clients (id, name, created_at)
VALUES ($1, $2, $3)
`

type CreateClientParams struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) error {
	_, err := q.db.Exec(ctx, createClient, arg.ID, arg.Name, arg.CreatedAt)
	return err
}
