// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package dbgen

import (
	"context"
)

const checkAuthSchema = `-- name: CheckAuthSchema :exec
SELECT k.id, u.id, s.id
FROM api_keys k, users u, auth_sessions s
LIMIT 0
`

// Validate connectivity, schema availability, and permissions without fetching rows.
func (q *Queries) CheckAuthSchema(ctx context.Context) error {
	_, err := q.db.Exec(ctx, checkAuthSchema)
	return err
}
