// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: limits.sql

package dbgen

import (
	"context"
)

const getTenantPolicy = `-- name: GetTenantPolicy :one
SELECT max_concurrent_sessions, max_session_seconds, session_requests_per_minute
FROM clients WHERE id = $1
`

type GetTenantPolicyRow struct {
	MaxConcurrentSessions    int32
	MaxSessionSeconds        int32
	SessionRequestsPerMinute int32
}

func (q *Queries) GetTenantPolicy(ctx context.Context, clientID string) (GetTenantPolicyRow, error) {
	row := q.db.QueryRow(ctx, getTenantPolicy, clientID)
	var i GetTenantPolicyRow
	err := row.Scan(&i.MaxConcurrentSessions, &i.MaxSessionSeconds, &i.SessionRequestsPerMinute)
	return i, err
}

const updateTenantPolicy = `-- name: UpdateTenantPolicy :execrows
UPDATE clients
SET max_concurrent_sessions = $1,
    max_session_seconds = $2,
    session_requests_per_minute = $3
WHERE id = $4
`

type UpdateTenantPolicyParams struct {
	MaxConcurrentSessions    int32
	MaxSessionSeconds        int32
	SessionRequestsPerMinute int32
	ClientID                 string
}

func (q *Queries) UpdateTenantPolicy(ctx context.Context, arg UpdateTenantPolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTenantPolicy,
		arg.MaxConcurrentSessions,
		arg.MaxSessionSeconds,
		arg.SessionRequestsPerMinute,
		arg.ClientID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
