// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"
)

type ApiKey struct {
	ID        string
	ClientID  string
	Name      string
	Digest    []byte
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt *time.Time
}

type AuthSession struct {
	ID        string
	UserID    string
	Digest    []byte
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt *time.Time
}

type Client struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type User struct {
	ID           string
	ClientID     string
	Name         string
	Email        string
	PasswordHash []byte
	CreatedAt    time.Time
}
