// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	// Validate connectivity, schema availability, and permissions without fetching rows.
	CheckAuthSchema(ctx context.Context) error
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error
	CreateClient(ctx context.Context, arg CreateClientParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	FindAPIKey(ctx context.Context, id string) (ApiKey, error)
	FindSession(ctx context.Context, id string) (FindSessionRow, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	ListAPIKeys(ctx context.Context, clientID string) ([]ListAPIKeysRow, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
