// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO auth_sessions (id, user_id, digest, created_at, expires_at)
VALUES (
    $1, $2, $3,
    $4, $5
)
`

type CreateSessionParams struct {
	ID        string
	UserID    string
	Digest    []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Digest,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const findSession = `-- name: FindSession :one
SELECT
    s.id AS session_id,
    s.user_id,
    s.digest,
    s.created_at AS session_created_at,
    s.expires_at,
    s.revoked_at,
    u.client_id,
    u.name,
    u.email,
    u.created_at AS user_created_at
FROM auth_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1
`

type FindSessionRow struct {
	SessionID        string
	UserID           string
	Digest           []byte
	SessionCreatedAt time.Time
	ExpiresAt        time.Time
	RevokedAt        *time.Time
	ClientID         string
	Name             string
	Email            string
	UserCreatedAt    time.Time
}

func (q *Queries) FindSession(ctx context.Context, id string) (FindSessionRow, error) {
	row := q.db.QueryRow(ctx, findSession, id)
	var i FindSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.Digest,
		&i.SessionCreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ClientID,
		&i.Name,
		&i.Email,
		&i.UserCreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, $1::timestamptz)
WHERE id = $2 AND user_id = $3
`

type RevokeSessionParams struct {
	RevokedAt time.Time
	ID        string
	UserID    string
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.RevokedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
